### ISSUE TITLE
Weird DOM behavior when code splitting

### ISSUE THREAD

**Issue by Schachte** [maxam2017/react-18-ssr#2]
First off, thanks for publishing this repo. It's straight forward and better written than Meta's.

I wanted to post this in case it helps anyone and also get feedback. I am trying to build a pure React SSR setup like yourself but using a bundler (Rollup) for more optimized code splitting on the client (goodbye Next.JS 👋) . I ran into 3 problems with hacks to resolve but wish I didn't have to, so curious if I'm missing something. 

1. When I use the HTML component when the client bundle loads, I get UI hydration mismatch errors from the server. To resolve, I check to see if I'm client and if I am, I only hydrate `<App />` and not the surrounding HTML. 

_Conditional hydration example_:
```tsx
import AppRoutes from "./AppRoutes";
import Html from "./components/Html";

export default function App() {
  if (typeof window !== "undefined") {
    return <AppRoutes />;
  }
  return (
    <Html title="React SSR Demo">
      <AppRoutes />
    </Html>
  );
}
```

2. I got non-deterministic behavior with `onShellReady` when streaming my components that use dynamic imports. On initial page load the DOM would be just a white page and the rendered HTML would say JavaScript not enabled. To resolve I used `onAllReady`. This is fine for SEO optimized applications for full SSG, but it's not ideal for SSR applications trying to optimize hydration time.

_Example SSR handling with Express_
```tsx
app.get("*", async (req, res) => {
  console.log(req.url);
  const stream = ReactDOMServer.renderToPipeableStream(
    <StaticRouter location={req.url}>
      <App />
    </StaticRouter>,
    {
      onAllReady() {
        res.set("content-type", "text/html");
        stream.pipe(res);
        res.end();
      },
      onError() {},
    }
  );
  setTimeout(() => {
    stream.abort();
  }, 5000);
});
```

3. I actually have always found the `bootstrapScripts` on the `renderToPipeableStream` API to be awkward. It seems, at least to me, it kind of randomly injects the hydration script randomly into the DOM. Unfortunately, when using it here I could only get it to show up after the root `html` tag which isn't valid.

I removed that line completely and just modified the `Html` component like so:

```tsx
import { PropsWithChildren } from "react";

type HtmlProps = PropsWithChildren<{ title: string }>;

export default function Html({ children, title }: HtmlProps) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-react-app"
        />
        <title>{title}</title>
      </head>
      <body>
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<b>Enable JavaScript to run this app.</b>`,
          }}
        />
        <div id="root">{children}</div>
        <script defer async type="module" src="/index.js"></script>
      </body>
    </html>
  );
}

```

I'll try and post a repo soon for complete repro, but open to any feedback or code!

**Comment by maxam2017** [comment]
Hi @Schachte, thanks for using my project and sorry for very late reply 🙇 

> 1. When I use the HTML component when the client bundle loads, I get UI hydration mismatch errors from the server. To resolve, I check to see if I'm client and if I am, I only hydrate <App /> and not the surrounding HTML.

This was my mistake in misusing the Html component. It should only render on the server side because we only render/hydrate React inside `<div id="root">...</div>`.

This is my fix: render HTML via ReactDOMServer only
https://github.com/maxam2017/react-18-ssr/blob/f3b3a6f800bd8bc267c99709bb0e621787013d1d/server.tsx#L29-L34



> 2.  got non-deterministic behavior with onShellReady when streaming my components that use dynamic imports. On initial page load the DOM would be just a white page and the rendered HTML would say JavaScript not enabled. To resolve I used onAllReady. This is fine for SEO optimized applications for full SSG, but it's not ideal for SSR applications trying to optimize hydration time.

The weird behavior occurred because I misused `ctx.res.end()`.
```tsx
       onShellReady() {
          ctx.respond = false;
          ctx.res.statusCode = didError ? 500 : 200;
          ctx.response.set('content-type', 'text/html');

          stream.pipe(ctx.res);
          ctx.res.end(); // ❌ signals the server to finish sending the response which make stream directly close.
        },
```

Here, we directly invoke the end function, which signals the server to finish sending the response. 
However, we dynamically import the component, so at first time server-rendering the component is not ready to load before end signal.

The fix is to remove the ctx.res.end() because when we pipe the stream to ctx.res, it will automatically trigger the end event when the stream is done.
https://github.com/maxam2017/react-18-ssr/blob/f3b3a6f800bd8bc267c99709bb0e621787013d1d/server.tsx#L37-L43

> 3. I actually have always found the bootstrapScripts on the renderToPipeableStream API to be awkward. It seems, at least to me, it kind of randomly injects the hydration script randomly into the DOM. Unfortunately, when using it here I could only get it to show up after the root html tag which isn't valid.

Directly writing into the Html template component is also a good approach and more flexible. However, I think both approaches should work correctly :)

p.s. I have already pushed these fixes to the master branch. Feel free to check them out.

**Comment by Schachte** [comment]
@maxam2017 wow nice, thanks for the detailed reply!
